theme = "educapad-hugo-ui"
baseurl = "https://www.educapad.fr/"
languageCode = "fr-fr"
title = "EducaPad"

googleAnalytics = ""
disqusShortname = ""

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true

[permalinks]
    post = "/articles/:slug/"

[[menu.main]]
    name = "Axiomes"
    url = "/axiomes/"
    pre = "<i class='fa fa-tasks'></i>"
    weight = 1
    identifier = "axiomes"
[[menu.main]]
    name = "Solutions"
    url = "/solutions/"
    pre = "<i class='fa fa-university'></i>"
    weight = 2
    identifier = "solutions"


[[menu.main]]
    name = "Vision Globale"
    pre = "<i class='fa fa-location-arrow'></i>"
    url = "/axiomes/vision/"
    weight = 1
    parent = "axiomes"
[[menu.main]]
    name = "iPad"
    pre = "<i class='fa fa-tablet'></i>"
    url = "/axiomes/ipad/"
    weight = 2
    parent = "axiomes"
[[menu.main]]
    name = "Google Suite"
    pre = "<i class='fa fa-google'></i>"
    url = "/axiomes/gsuite/"
    weight = 3
    parent = "axiomes"
[[menu.main]]
    name = "Workspace ONE"
    pre = "<i class='fa fa-briefcase'></i>"
    url = "/axiomes/ws1/"
    weight = 4
    parent = "axiomes"



[[menu.main]]
    name = "Infrastructure"
    pre = "<i class='fa fa-server'></i>"
    url = "/solutions/infra/"
    weight = 1
    parent = "solutions"
[[menu.main]]
    name = "Service d'annuaire"
    pre = "<i class='fa fa-sitemap'></i>"
    url = "/solutions/annuaire/"
    weight = 2
    parent = "solutions"
[[menu.main]]
    name = "Gestionnaire de terminaux"
    pre = "<i class='fa fa-tablet'></i>"
    url = "/solutions/uem/"
    weight = 3
    parent = "solutions"
[[menu.main]]
    name = "Fédération d'identité"
    pre = "<i class='fa fa-id-badge'></i>"
    url = "/solutions/idp/"
    weight = 4
    parent = "solutions"
[[menu.main]]
    name = "Impression"
    pre = "<i class='fa fa-print'></i>"
    url = "/solutions/impression/"
    weight = 5
    parent = "solutions"
[[menu.main]]
    name = "Distribution"
    pre = "<i class='fa fa-gift'></i>"
    url = "/solutions/distribution/"
    weight = 6
    parent = "solutions"
    
    
    
[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/abelionni"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/abelionni"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "Abelionni"
    pre = "<i class='fa fa-building'></i>"
    url = "https://www.abelionni.com/"
    weight = 3
[[menu.footer]]
    identifier = "legal"
    name = "Mentions légales"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "/mentions-legales"
    weight = 4


[params]
    background = "/img/bg11.jpg"
    tint = "orange"
    custom_css = ["css/highlight.min.css"]
    custom_js = []
    date_format = "2 January 2006"
    description = "iPad et Education"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

