version: 2.1
jobs:
  build:
    docker:
      - image: ygini/hugo
    steps:
      - checkout
      - run:
          name: Set git identity
          command: git config user.email "circleci@educapad.fr" && git config user.name "Circle CI Engine"
      - run:
          name: Get subomdules
          command: git submodule sync && git submodule update --init
      - run: 
          name: Generate Static Website
          command: hugo -v -s . -d public
      - run:
          name: Deploy Static Website to gh-pages branch
          command: gh-pages --dist public
