version: 2.1
jobs:
  build:
    docker:
      - image: ygini/hugo
    steps:
      - checkout
      - run:
          name: Set git identity
          command: git config user.email "circleci@educapad.fr" && git config user.name "Circle CI Engine"
      - run:
          name: Get subomdules
          command: git submodule sync && git submodule update --init
      - run: 
          name: Generate Static Website
          command: hugo -v -s . -d public
      - add_ssh_keys:
          fingerprints:
            - "81:c5:6c:be:bc:a8:41:77:9f:62:92:72:a1:48:6d:6d"
      - run:
          name: Deploy Static Website to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Circle CI Publication" --dist public
